# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _coast_wrapper
else:
    import _coast_wrapper

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class MCorsikaReader(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, filename, verbose=0):
        _coast_wrapper.MCorsikaReader_swiginit(self, _coast_wrapper.new_MCorsikaReader(filename, verbose))

    def GetRun(self, run):
        return _coast_wrapper.MCorsikaReader_GetRun(self, run)

    def GetShower(self, shower):
        return _coast_wrapper.MCorsikaReader_GetShower(self, shower)

    def GetData(self, data):
        return _coast_wrapper.MCorsikaReader_GetData(self, data)

    def GetShowerSummary(self, summary):
        return _coast_wrapper.MCorsikaReader_GetShowerSummary(self, summary)
    __swig_destroy__ = _coast_wrapper.delete_MCorsikaReader

# Register MCorsikaReader in _coast_wrapper:
_coast_wrapper.MCorsikaReader_swigregister(MCorsikaReader)

class MRunHeader(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _coast_wrapper.MRunHeader_swiginit(self, _coast_wrapper.new_MRunHeader(*args))
    __swig_destroy__ = _coast_wrapper.delete_MRunHeader

    def GetRunID(self):
        return _coast_wrapper.MRunHeader_GetRunID(self)

    def GetDateStart(self):
        return _coast_wrapper.MRunHeader_GetDateStart(self)

    def GetVersion(self):
        return _coast_wrapper.MRunHeader_GetVersion(self)

    def GetNObservationLevels(self):
        return _coast_wrapper.MRunHeader_GetNObservationLevels(self)

    def GetObservationHeight(self, index):
        return _coast_wrapper.MRunHeader_GetObservationHeight(self, index)

    def GetSpectralSlope(self):
        return _coast_wrapper.MRunHeader_GetSpectralSlope(self)

    def GetEMin(self):
        return _coast_wrapper.MRunHeader_GetEMin(self)

    def GetEMax(self):
        return _coast_wrapper.MRunHeader_GetEMax(self)

    def GetFlagEGS4(self):
        return _coast_wrapper.MRunHeader_GetFlagEGS4(self)

    def GetFlagNKG(self):
        return _coast_wrapper.MRunHeader_GetFlagNKG(self)

    def GetCutoffHadrons(self):
        return _coast_wrapper.MRunHeader_GetCutoffHadrons(self)

    def GetCutoffMuons(self):
        return _coast_wrapper.MRunHeader_GetCutoffMuons(self)

    def GetCutoffElectrons(self):
        return _coast_wrapper.MRunHeader_GetCutoffElectrons(self)

    def GetCutoffPhotons(self):
        return _coast_wrapper.MRunHeader_GetCutoffPhotons(self)

    def GetSamplingPlanePointX(self):
        return _coast_wrapper.MRunHeader_GetSamplingPlanePointX(self)

    def GetSamplingPlanePointY(self):
        return _coast_wrapper.MRunHeader_GetSamplingPlanePointY(self)

    def GetSamplingPlanePointZ(self):
        return _coast_wrapper.MRunHeader_GetSamplingPlanePointZ(self)

    def GetSamplingPlaneNormalX(self):
        return _coast_wrapper.MRunHeader_GetSamplingPlaneNormalX(self)

    def GetSamplingPlaneNormalY(self):
        return _coast_wrapper.MRunHeader_GetSamplingPlaneNormalY(self)

    def GetSamplingPlaneNormalZ(self):
        return _coast_wrapper.MRunHeader_GetSamplingPlaneNormalZ(self)

    def GetAtmosphereLayerBoundary(self, index):
        return _coast_wrapper.MRunHeader_GetAtmosphereLayerBoundary(self, index)

    def GetAtmosphereA(self, index):
        return _coast_wrapper.MRunHeader_GetAtmosphereA(self, index)

    def GetAtmosphereB(self, index):
        return _coast_wrapper.MRunHeader_GetAtmosphereB(self, index)

    def GetAtmosphereC(self, index):
        return _coast_wrapper.MRunHeader_GetAtmosphereC(self, index)

    def GetConstNFLAIN(self):
        return _coast_wrapper.MRunHeader_GetConstNFLAIN(self)

    def GetConstNFLDIF(self):
        return _coast_wrapper.MRunHeader_GetConstNFLDIF(self)

    def GetConstNFLPI0(self):
        return _coast_wrapper.MRunHeader_GetConstNFLPI0(self)

    def GetConstNFLPIF(self):
        return _coast_wrapper.MRunHeader_GetConstNFLPIF(self)

    def GetConstNFLCHE(self):
        return _coast_wrapper.MRunHeader_GetConstNFLCHE(self)

    def GetConstNFRAGM(self):
        return _coast_wrapper.MRunHeader_GetConstNFRAGM(self)

# Register MRunHeader in _coast_wrapper:
_coast_wrapper.MRunHeader_swigregister(MRunHeader)

class MEventHeader(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _coast_wrapper.MEventHeader_swiginit(self, _coast_wrapper.new_MEventHeader(*args))
    __swig_destroy__ = _coast_wrapper.delete_MEventHeader

    def GetEventNumber(self):
        return _coast_wrapper.MEventHeader_GetEventNumber(self)

    def GetParticleId(self):
        return _coast_wrapper.MEventHeader_GetParticleId(self)

    def GetEnergy(self):
        return _coast_wrapper.MEventHeader_GetEnergy(self)

    def GetStartingAltitude(self):
        return _coast_wrapper.MEventHeader_GetStartingAltitude(self)

    def GetFirstTarget(self):
        return _coast_wrapper.MEventHeader_GetFirstTarget(self)

    def GetZFirst(self):
        return _coast_wrapper.MEventHeader_GetZFirst(self)

    def GetPx(self):
        return _coast_wrapper.MEventHeader_GetPx(self)

    def GetPy(self):
        return _coast_wrapper.MEventHeader_GetPy(self)

    def GetPz(self):
        return _coast_wrapper.MEventHeader_GetPz(self)

    def GetTheta(self):
        return _coast_wrapper.MEventHeader_GetTheta(self)

    def GetPhi(self):
        return _coast_wrapper.MEventHeader_GetPhi(self)

    def GetNRandomSequences(self):
        return _coast_wrapper.MEventHeader_GetNRandomSequences(self)

    def GetSeed(self, index):
        return _coast_wrapper.MEventHeader_GetSeed(self, index)

    def GetInitialCallsMod(self, index):
        return _coast_wrapper.MEventHeader_GetInitialCallsMod(self, index)

    def GetInitialCallsDiv(self, index):
        return _coast_wrapper.MEventHeader_GetInitialCallsDiv(self, index)

    def GetRunNumber(self):
        return _coast_wrapper.MEventHeader_GetRunNumber(self)

    def GetDateStart(self):
        return _coast_wrapper.MEventHeader_GetDateStart(self)

    def GetVersion(self):
        return _coast_wrapper.MEventHeader_GetVersion(self)

    def GetNObservationLevels(self):
        return _coast_wrapper.MEventHeader_GetNObservationLevels(self)

    def GetObservationHeight(self, index):
        return _coast_wrapper.MEventHeader_GetObservationHeight(self, index)

    def GetSpectralSlope(self):
        return _coast_wrapper.MEventHeader_GetSpectralSlope(self)

    def GetEMin(self):
        return _coast_wrapper.MEventHeader_GetEMin(self)

    def GetEMax(self):
        return _coast_wrapper.MEventHeader_GetEMax(self)

    def GetCutoffHadrons(self):
        return _coast_wrapper.MEventHeader_GetCutoffHadrons(self)

    def GetCutoffMuons(self):
        return _coast_wrapper.MEventHeader_GetCutoffMuons(self)

    def GetCutoffElectrons(self):
        return _coast_wrapper.MEventHeader_GetCutoffElectrons(self)

    def GetCutoffPhotons(self):
        return _coast_wrapper.MEventHeader_GetCutoffPhotons(self)

    def GetNFLAIN(self):
        return _coast_wrapper.MEventHeader_GetNFLAIN(self)

    def GetNFLDIF(self):
        return _coast_wrapper.MEventHeader_GetNFLDIF(self)

    def GetNFLPI0(self):
        return _coast_wrapper.MEventHeader_GetNFLPI0(self)

    def GetNFLPIF(self):
        return _coast_wrapper.MEventHeader_GetNFLPIF(self)

    def GetNFLCHE(self):
        return _coast_wrapper.MEventHeader_GetNFLCHE(self)

    def GetNFRAGM(self):
        return _coast_wrapper.MEventHeader_GetNFRAGM(self)

    def GetBx(self):
        return _coast_wrapper.MEventHeader_GetBx(self)

    def GetBz(self):
        return _coast_wrapper.MEventHeader_GetBz(self)

    def GetFlagEGS4(self):
        return _coast_wrapper.MEventHeader_GetFlagEGS4(self)

    def GetFlagNKG(self):
        return _coast_wrapper.MEventHeader_GetFlagNKG(self)

    def GetHadronicLowEModell(self):
        return _coast_wrapper.MEventHeader_GetHadronicLowEModell(self)

    def GetHadronicHighEModell(self):
        return _coast_wrapper.MEventHeader_GetHadronicHighEModell(self)

    def GetFlagCherenkov(self):
        return _coast_wrapper.MEventHeader_GetFlagCherenkov(self)

    def GetFlagNeutrino(self):
        return _coast_wrapper.MEventHeader_GetFlagNeutrino(self)

    def GetFlagCurved(self):
        return _coast_wrapper.MEventHeader_GetFlagCurved(self)

    def GetFlagComputer(self):
        return _coast_wrapper.MEventHeader_GetFlagComputer(self)

    def GetThetaMin(self):
        return _coast_wrapper.MEventHeader_GetThetaMin(self)

    def GetThetaMax(self):
        return _coast_wrapper.MEventHeader_GetThetaMax(self)

    def GetPhiMin(self):
        return _coast_wrapper.MEventHeader_GetPhiMin(self)

    def GetPhiMax(self):
        return _coast_wrapper.MEventHeader_GetPhiMax(self)

    def GetCherenkovBunch(self):
        return _coast_wrapper.MEventHeader_GetCherenkovBunch(self)

    def GetCherenkovNumberX(self):
        return _coast_wrapper.MEventHeader_GetCherenkovNumberX(self)

    def GetCherenkovNumberY(self):
        return _coast_wrapper.MEventHeader_GetCherenkovNumberY(self)

    def GetCherenkovGridX(self):
        return _coast_wrapper.MEventHeader_GetCherenkovGridX(self)

    def GetCherenkovGridY(self):
        return _coast_wrapper.MEventHeader_GetCherenkovGridY(self)

    def GetCherenkovDetectorX(self):
        return _coast_wrapper.MEventHeader_GetCherenkovDetectorX(self)

    def GetCherenkovDetectorY(self):
        return _coast_wrapper.MEventHeader_GetCherenkovDetectorY(self)

    def GetCherenkovOutputFlag(self):
        return _coast_wrapper.MEventHeader_GetCherenkovOutputFlag(self)

    def GetArrayRotation(self):
        return _coast_wrapper.MEventHeader_GetArrayRotation(self)

    def GetFlagExtraMuonInformation(self):
        return _coast_wrapper.MEventHeader_GetFlagExtraMuonInformation(self)

    def GetMultipleScatteringStep(self):
        return _coast_wrapper.MEventHeader_GetMultipleScatteringStep(self)

    def GetCherenkovBandwidthMin(self):
        return _coast_wrapper.MEventHeader_GetCherenkovBandwidthMin(self)

    def GetCherenkovBandwidthMax(self):
        return _coast_wrapper.MEventHeader_GetCherenkovBandwidthMax(self)

    def GetNUsesOfEvent(self):
        return _coast_wrapper.MEventHeader_GetNUsesOfEvent(self)

    def GetCherenkovCoreX(self, index):
        return _coast_wrapper.MEventHeader_GetCherenkovCoreX(self, index)

    def GetCherenkovCoreY(self, index):
        return _coast_wrapper.MEventHeader_GetCherenkovCoreY(self, index)

    def GetFlagSIBYLL(self):
        return _coast_wrapper.MEventHeader_GetFlagSIBYLL(self)

    def GetFlagSIBYLLCross(self):
        return _coast_wrapper.MEventHeader_GetFlagSIBYLLCross(self)

    def GetFlagQGSJET(self):
        return _coast_wrapper.MEventHeader_GetFlagQGSJET(self)

    def GetFlagQGSJETCross(self):
        return _coast_wrapper.MEventHeader_GetFlagQGSJETCross(self)

    def GetFlagDPMJET(self):
        return _coast_wrapper.MEventHeader_GetFlagDPMJET(self)

    def GetFlagDPMJETCross(self):
        return _coast_wrapper.MEventHeader_GetFlagDPMJETCross(self)

    def GetFlagVENUSCross(self):
        return _coast_wrapper.MEventHeader_GetFlagVENUSCross(self)

    def GetFlagMuonMultiple(self):
        return _coast_wrapper.MEventHeader_GetFlagMuonMultiple(self)

    def GetNKGRadialRange(self):
        return _coast_wrapper.MEventHeader_GetNKGRadialRange(self)

    def GetEFractionThinningH(self):
        return _coast_wrapper.MEventHeader_GetEFractionThinningH(self)

    def GetEFractionThinningEM(self):
        return _coast_wrapper.MEventHeader_GetEFractionThinningEM(self)

    def GetWMaxHadronic(self):
        return _coast_wrapper.MEventHeader_GetWMaxHadronic(self)

    def GetWMaxEM(self):
        return _coast_wrapper.MEventHeader_GetWMaxEM(self)

    def GetRMaxThinning(self):
        return _coast_wrapper.MEventHeader_GetRMaxThinning(self)

    def GetInnerAngle(self):
        return _coast_wrapper.MEventHeader_GetInnerAngle(self)

    def GetOuterAngle(self):
        return _coast_wrapper.MEventHeader_GetOuterAngle(self)

    def GetTransitionEnergy(self):
        return _coast_wrapper.MEventHeader_GetTransitionEnergy(self)

    def GetSkimmingIncidence(self):
        return _coast_wrapper.MEventHeader_GetSkimmingIncidence(self)

    def GetSkimmingAltitude(self):
        return _coast_wrapper.MEventHeader_GetSkimmingAltitude(self)

    def GetStartingHeight(self):
        return _coast_wrapper.MEventHeader_GetStartingHeight(self)

# Register MEventHeader in _coast_wrapper:
_coast_wrapper.MEventHeader_swigregister(MEventHeader)



